image: docker:stable

before_script:
  #- docker -H tcp://192.168.1.176:2375 info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

services:
- docker:dind

stages:
  - deploy

deploy-prod:
  stage: deploy
  script:
    - docker stack deploy -c docker-compose.yml portainer
