version: '3.5'
services:

  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints:
          - "node.platform.os == linux"

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.role == manager"
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.rule=Host:portainer.vlekh.net, http://portainer.vlekh.net"
        - "traefik.backend=portainer_portainer"
        - "traefik.docker.network=traefik"
        - "traefik.entryPoint=https"
        - "traefik.port=9000"
    ports:
      - 9000:9000
    networks:
      - traefik
      - agent_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      
volumes:
  portainer_data:

networks:
  traefik:
    external: true
    name: traefik
  agent_network:
    driver: overlay
    attachable: true
